config/routes.rb
Litchfield::Application.routes.draw do
    devise_for :users do
      get "/sign_in" => "devise/sessions#new"
      get "/sign_out" => "devise/sessions#destroy"
    end
    match 'sign_up' => 'admin#new_user'
    match '/create_user', :to => 'admin#create_user', :via => :post
    match 'edit_user' => 'admin#edit_user'
    match '/update_user', :to => 'admin#update_user', :via => :post
    match '/destroy_user', :to => 'admin#destroy_user', :via => :post
  
    match '/admin', :to => 'admin#index'
  
    get 'contact_us' => 'home#contact_us'
    post 'home/mail' => 'home#mail'
  
    match 'admin/validate_date' => 'admin#validate_date'
  
    match 'search/advanced' => 'search#advanced'
    match 'search/autocomplete' => 'search#autocomplete'
    match 'browse' => 'browse#index'
    match 'search' => 'search#index'
    match 'search/help' => 'search#help'
    match 'about' => 'search#about'
    match 'studies' => 'studies#index'
    match 'studies/history' => 'studies#history'
    match 'studies/history_school' => 'studies#history_school'
    match 'studies/history_lfa' => 'studies#history_lfa'
    match 'studies/lls_bibliography' => 'studies#lls_bibliography'
    match 'studies/lfa_bibliography' => 'studies#lfa_bibliography'
    match 'admin' => 'admin#index'
    match 'students/why' => 'students#why'
    match 'students/limit' => 'students#limit'
    match 'admin/new_row' => 'admin#new_row'
  
    match 'test_exception_notifier' => 'application#test_exception_notifier'
  
    match 'students/export_data' => 'students#export_data'
    match 'materials/export_data' => 'materials#export_data'
    match 'admin/account_maintenance' => 'admin#account_maintenance'
    post 'materials/add_transcription/:id' => 'materials#add_transcription'
    post 'materials/add_image/:id' => 'materials#add_image'
    post 'materials/remove_transcription/:id' => 'materials#remove_transcription'
    post 'materials/remove_image/:id' => 'materials#remove_image'
  
    resources :admin
  
    resources :materials
  
    resources :students
  
    root :to => "home#index"
  
  
  
  
  
  
  
  
  
  
  
end
  

app/helpers/students_helper.rb
module StudentsHelper
	def list_professions(professions)
		return "" if professions == nil
		profs = []
		professions.each {|pro|
			profs.push(pro.title)
		}
		return profs.join("; ")
	end
	
	def list_residences(residences)
		return "" if residences == nil
		homes = []
		residences.each {|res|
			str = ""
			str += "#{res.town}, " if res.town != nil && res.town.length > 0
			str += "#{res.state}"
			str += " #{res.country}" if res.country != nil && res.country.length > 0 && res.country != "United States"
			homes.push(str)
		}
		return homes.join("<br />")
	end

	def list_marriages(marriages)
		return "" if marriages == nil
		marriage = []
		marriages.each {|rec|
			if rec['spouse_id']
				spouse = Student.find_by_id(rec['spouse_id'])
				if spouse
					marriage.push("#{spouse.name} (#{rec['marriage_date'] && rec['marriage_date'].length > 0 ? rec['marriage_date'] : 'unknown' })")
				end
			else
				marriage.push("Unknown (#{rec['marriage_date'] && rec['marriage_date'].length > 0 ? rec['marriage_date'] : 'unknown' })")
			end
		}
		return marriage.join("<br />")
	end

	def list_govt_posts(posts, branch)
		return "" if posts == nil
		lines = []
		posts.each {|rec|
			if rec.which == branch
				lines.push("#{rec.title} #{rec.modifier} #{"(#{rec.location})" if rec.location && rec.location.length > 0} #{rec.time_span}")
			end
		}
		return lines.join("<br />")
	end

	def list_offsite_materials(list)
		return "" if list == nil || list.length == 0
		lines = []
		list.each {|rec|
			lines.push(link_to(rec.name, rec.url))
		}
		return lines.join("<br />")
	end

	def name_row(name, is_editing, typ)
		if is_editing
			return "Editing #{typ}: #{name}"
		else
			return name
		end
	end
	
	def name_row_edit(name, is_editing, typ)
		if is_editing
			return standard_row("Name:", text_field(typ, 'original_name', { :value => name }))
		else
			return ""
		end
	end

	def hometown_row(label, rec, is_editing)
		if is_editing
			data = "Town:" + create_input_widget(rec.home_town, 'place_input', "student", :home_town, 'town') + "State:" + create_input_widget(rec.home_state, 'state_input', "student", :home_town, 'state') + "Country:" + create_input_widget(rec.home_country, 'place_input', "student", :home_town, 'country')
		else
			if (rec.home_town == nil || rec.home_town.length == 0) && (rec.home_state == nil || rec.home_state.length == 0) && (rec.home_country == nil || rec.home_country.length == 0)
				return ""
			end
			data = ""
			data += "#{rec.home_town}, " if rec.home_town != nil && rec.home_town.length > 0
			data += "#{rec.home_state}"
			data += " #{rec.home_country}" if rec.home_country != nil && rec.home_country.length > 0 && rec.home_country != "United States"
		end
		html = "<div class='student_label'>#{label}</div><div class='student_data'>#{data}</div>\n"
		return raw(html)
	end

	def removable_row(content, tooltip, id, klass = nil)
		if klass == nil
			klass = "removable_row"
		else
			klass += " removable_row"
		end
		content_tag(:div, raw(content + remove_item_div(tooltip, id)), { :id => id, :class => klass })
	end

	def insert_row(id, content = "")
		content_tag(:div, content, { :id => id })
	end

	def removable_tr(content, tooltip, id)
		content_tag(:tr, raw(content + content_tag(:td, remove_item_div(tooltip, id))), { :id => id })
	end

	def wrap_addable(label, data, type, next_id, hint)
		if next_id > 0
			data += insert_row("insert_#{type}", '')
		else
			data += insert_row("insert_#{type}", content_tag(:span, hint, { :class => 'none_defined'}))
		end
		html = standard_row(label, data) + add_item_div(label, url_for({ :controller => "admin", :action => "new_row", :type => type, :el => "insert_#{type}", :id => "#{next_id}"}))
		return raw(html)

	end

	def wrap_nonaddable(label, data, type, next_id, hint)
		if next_id > 0
			data += insert_row("insert_#{type}", '')
		else
			data += insert_row("insert_#{type}", content_tag(:span, hint, { :class => 'none_defined'}))
		end
		html = standard_row(label, data)
		return raw(html)

	end

	def residences_row(label, recs, is_editing, typ)
		return student_row(label, list_residences(recs), is_editing, typ, :none, :none) if !is_editing

		data = ""
		recs.each_with_index {|rec, i|
			data += one_residence_row(typ, rec.town, rec.state, rec.country, i)
		}
		return wrap_addable(label, data, "residence", recs.length, "None added")
	end

	def marriages_row(label, recs, is_editing, typ)
		return student_row(label, list_marriages(recs), is_editing, typ, :none, :none) if !is_editing

		data = ""
		recs.each_with_index {|rec, i|
			name = rec['spouse_id'] ? Student.find(rec['spouse_id']).name : 'Unknown'
			data += one_marriage_row(typ, name, rec['marriage_date'], i)
		}
		return wrap_addable(label, data, "marriage", recs.length, "None added")
	end
	
	def govt_post_row(label, recs, is_editing, typ, branch, sel_list)
		return student_row(label, list_govt_posts(recs, branch), is_editing, typ, :none, :none, sel_list) if !is_editing

		this_branch = []
		recs.each {|rec|
			this_branch.push(rec) if rec.which == branch
		}
		data = ""
		this_branch.each_with_index {|rec, i|
			data += one_govt_post_row(typ, branch, sel_list, rec.title, rec.modifier, rec.location, rec.time_span, i, admin_signed_in?)
		}
		return wrap_addable(label, data, "govt_post_#{branch}", this_branch.length, "None added")
	end

	def offsite_materials_row(student, is_editing)
		return student_row("", list_offsite_materials(student.offsite_materials), is_editing, "student", :is_stub, :none) if !is_editing

		data = ""
		student.offsite_materials.each_with_index {|material, i|
			data += one_offsite_material(material.name, material.url, i)
		}
		return wrap_addable("", data, "offsite_material", student.offsite_materials.length, "No objects associated")
	end

	def one_select_row(typ, field_name, i, options, sel, is_admin)
		select = removable_row(
			create_select_widget_with_writein(options, sel, typ, field_name, "#{i}", is_admin),
			"Remove #{field_name}", "multiselect_#{field_name}_#{i}")
		return content_tag(:div, select)
	end

	def one_people_row(data, typ, i)
		people = removable_row(
			create_autocomplete_widget('student', data, typ, 'assoc', "#{i}") +
			  raw("<br />") + content_tag(:span, 'Student Assoc: ') + create_input_widget('', "assoc_relationship", "material", 'assoc_relationship', "#{i}") +
			  content_tag(:span, 'Obj Assoc: ') + create_input_widget('', "assoc_material_comment", "material", 'assoc_material_comment', "#{i}"),
				'Remove person', "person_#{i}")
		return content_tag(:div, people)
	end

	def one_assoc_object_row(data, typ, i)
		people = removable_row(
			create_autocomplete_widget('material', data, typ, 'mat_assoc', "#{i}") +
			  raw("<br />") + content_tag(:span, 'This Assoc: ') + create_input_widget('', "mat_assoc_description1", "material", 'mat_assoc_description1', "#{i}") +
			  content_tag(:span, 'That Assoc: ') + create_input_widget('', "mat_assoc_description2", "material", 'mat_assoc_description2', "#{i}"),
				'Remove person', "person_#{i}")
		return content_tag(:div, people)
	end

	def one_residence_row(typ, town, state, country, i)
		return removable_row(
			"Town:" + create_input_widget(town, 'place_input', typ, 'residence', "#{i}", 'town') +
			"State:" + create_input_widget(state, 'state_input', typ, 'residence', "#{i}", 'state') +
			"Country:" + create_input_widget(country, 'place_input', typ, 'residence', "#{i}", 'country'),
		'Remove residence', "residence_#{i}")
	end

	def one_marriage_row(typ, name, date, i)
		id = make_name(typ, 'marriage', "#{i}", 'name')
		if name.length > 0
			removable_row(
				content_tag(:input, '', { :readonly => "readonly", :class => 'readonly_input', :name => id, :value => name }) +
					create_input_widget(date, 'marriage_date_input vague_date', typ, 'marriage', "#{i}", 'date') + content_tag(:span, '', { :class => 'date_error' }),
				'Remove marriage', "marriage_#{i}")
		else
			removable_row(
				create_autocomplete_widget('student', name, typ, 'marriage', "#{i}", 'name') +
					create_input_widget(date, 'marriage_date_input vague_date', typ, 'marriage', "#{i}", 'date') + content_tag(:span, '', { :class => 'date_error' }),
				'Remove marriage', "marriage_#{i}")
		end
	end

	def one_govt_post_row(typ, branch, sel_list, title, modifier, location, time_span, i, is_admin)
		removable_row(
			create_select_widget_with_writein(sel_list, title, typ, branch, "#{i}", is_admin) +
				content_tag(:span, 'Modifier: ') + create_input_widget(modifier, 'govt_input', typ, branch, "#{i}", 'modifier') + raw("<br />") +
				content_tag(:span, 'Location:') + create_input_widget(location, 'govt_input_left', typ, branch, "#{i}", 'location') +
				content_tag(:span, 'Years: ') + create_input_widget(time_span, 'govt_input', typ, branch, "#{i}", 'time_span'),
			"Remove #{branch} post", "govt_post_#{branch}_#{i}")
	end

	def one_relationship_row(type, name, relationship, i)
		id = make_name(type, "relationship", "#{i}", "type")
		id2 = make_name(type, "relationship", "#{i}", "name")
		if name.length > 0
			removable_row(
				content_tag(:input, '', { :readonly => "readonly", :class => 'readonly_input', :name => id2, :value => name }) +
					relationship_choices(id, relationship),
				'Remove relative', "relationship_#{i}")
		else
			removable_row(
				create_autocomplete_widget('student', name, type, "relationship", "#{i}", "name") +
					relationship_choices(id, relationship),
				'Remove relative', "relationship_#{i}")
		end
	end

	def one_object_row(id, name, relationship, obj_assoc, i)
		if name.length > 0
			removable_row(
				content_tag(:input, '', { :type => 'hidden', :name => "student[material][#{i}][idd]", :value => id }) +
				  content_tag(:input, '', { :readonly => "readonly", :class => 'readonly_input', :value => name }) +
				  raw("<br />") + content_tag(:span, 'Student Assoc: ') + create_input_widget(relationship, '', 'student', 'material', "#{i}", 'relationship') +

app/views/students/_form.html.erb
<%#
# ------------------------------------------------------------------------
#     Copyright 2010 Litchfield Historical Society
# ----------------------------------------------------------------------------
# STUDENTS
%>
<%# form: params: bool is_editing %>
<% if params[:iterate] %>
<div style="position: absolute;top:220px;">
<%= link_to "Next", :controller => 'students', :action => 'show', :id => @student.id, :iterate => 'next' %><br />
<%= link_to "Next Img", :controller => 'students', :action => 'show', :id => @student.id, :iterate => 'next_img' %><br />
<%= link_to "Next Stub", :controller => 'students', :action => 'show', :id => @student.id, :iterate => 'next_stub' %></div>
<% end %>
<% gender = @student.gender=='F'?'Female':'Male' %>
<%= main_student_image(@student, gender, is_editing) %>
<% if user_signed_in? && !is_editing %>
<div class="edit_button">
	<%# = button_to("Delete Student", { :action => 'destroy', :id => @student.id },
            :confirm => "Are you sure you want to delete #{@student.name}?", :method => :delete, :class => 'confirm') if full_signed_in? %>
	<%= create_button("Delete", { :controller => 'students', :action => 'destroy', :id => @student.id }, 'delete_btn fxn_confirm', { 'data-confirm' => 'Are you sure you want to delete this student?', 'data-method' => 'delete' })  if full_signed_in? %>
	<%= create_button("Edit", edit_student_path(@student) + "?section=1", 'edit_btn') %>
</div>
<% end %>
<div class="student_data_div">
	<p class="student_name"><%= name_row(@student.original_name, is_editing, "Person") %></p>
</div>
<% if !is_editing %>
<hr />
<% end %>
<%= custom_error_messages_helper(@student) %>
<div id="edit_section_1" class="<%= 'hidden' if @show_1 != true %>">
<div class="student_data_div">
	<%= edit_collection(is_editing) %>
	<%= name_row_edit(@student.original_name, is_editing, "student") %>
	<%= student_row("Other Name:", @student.other_name, is_editing, "student", :other_name, :input) %>
	<%= student_row("Gender:", gender, is_editing, "student", :gender, :gender) %>
	<%= student_row("Born:", VagueDate.full(@student.born), is_editing, "student", :born, :date) %>
	<%= student_row("Died:", VagueDate.full(@student.died), is_editing, "student", :died, :date) %>
	<%= main_student_image_edit(@student, gender, is_editing, @materials) %>
	<%= edit_collection_end(is_editing) %>
	<%= edit_collection(is_editing) %>
<% if is_editing || (@student.home_town && (@student.home_town.length > 0 || @student.home_state.length > 0)) %>
	<%= hometown_row("Home Town:", @student, is_editing) %>
<% end %>
	<%= edit_collection_end(is_editing) %>
	<%= edit_collection(is_editing) %>
	<%= residences_row("Later Residences:", @student.residences, is_editing, "student") %>
	<%= edit_collection_end(is_editing) %>
	<%= edit_collection(is_editing) %>
	<%= marriages_row("Marriage(s):", @marriages, is_editing, "student") %>
	<%= edit_collection_end(is_editing) %>
	<%= edit_collection(is_editing) %>
	<%= student_row("Biographical Notes:", @student.biographical_notes, is_editing, "student", :biographical_notes, :string) %>
	<%= student_row("Quotes:", @student.quotes, is_editing, "student", :quotes, :string) %>
	<%= student_row("Additional Notes:", @student.additional_notes, is_editing, "student", :additional_notes, :string) %>
	<%= student_row("Private Notes:", @student.private_notes, is_editing, "student", :private_notes, :string) if user_signed_in? %>
	<%= edit_collection_end(is_editing) %>
</div>
<% if !is_editing %>
<hr class="clear_left" />
<% end %>
</div>
<% if user_signed_in? && !is_editing %>
<div class="edit_button">
	<%= create_button("Edit", edit_student_path(@student) + "?section=2", 'edit_btn') %>
</div>
<% end %>
<div id="edit_section_2" class="<%= 'hidden' if @show_2 != true %>">
<% if user_signed_in? || @student.has_education_category() %>
<div class="student_data_div">
	<div class="student_data_header">Education</div>
<% if is_editing || @student.has_education_category() %>
	<%= edit_collection(is_editing) %>
	<%= years_attended_row(@student, is_editing) %>
	<%= edit_collection_end(is_editing) %>
	<%= edit_collection(is_editing) %>
	<%= student_row("Other Education:", @student.other_education, is_editing, "student", :other_education, :string) %>
	<%= student_row("Room and Board:", @student.room_and_board, is_editing, "student", :room_and_board, :string) %>
	<%= edit_collection_end(is_editing) %>
<% end %>
</div>
<% if !is_editing %>
<hr class="clear_left" />
<% end %>
<% end %>
</div>
<% if user_signed_in? && !is_editing %>
<div class="edit_button">
	<%= create_button("Edit", edit_student_path(@student) + "?section=3", 'edit_btn') %>
</div>
<% end %>
<div id="edit_section_3" class="<%= 'hidden' if @show_3 != true %>">
<% if user_signed_in? || @student.has_profession_category() %>
<div class="student_data_div">
	<div class="student_data_header">Profession / Service</div>
<% if is_editing || @student.has_profession_category() %>
	<%= edit_collection(is_editing) %>
	<%= student_row("Profession:", list_professions(@student.professions), is_editing, "student", :professions, :multiple_select, @professions) %>
	<%= edit_collection_end(is_editing) %>
	<%= edit_collection(is_editing) %>
	<%= student_row("Admitted To Bar:", @student.admitted_to_bar, is_editing, "student", :admitted_to_bar, :string) %>
	<%= student_row("Training with Other Lawyers:", @student.training_with_other_lawyers, is_editing, "student", :training_with_other_lawyers, :string) %>
	<%= edit_collection_end(is_editing) %>
	<%= edit_collection(is_editing) %>
	<%= student_row("Political Party:", list_professions(@student.political_parties), is_editing, "student", :political_parties, :multiple_select, @political_parties) %>
	<%= edit_collection_end(is_editing) %>
	<%= edit_collection(is_editing) %>
	<%= govt_post_row("Federal Posts:", @student.government_posts, is_editing, "student", 'Federal', @federal_posts) %>
	<%= student_row("Federal Committees:", @student.federal_committees, is_editing, "student", :federal_committees, :string) %>
	<%= edit_collection_end(is_editing) %>
	<%= edit_collection(is_editing) %>
	<%= govt_post_row("State Posts:", @student.government_posts, is_editing, "student", 'State', @state_posts) %>
	<%= student_row("State Committees:", @student.state_committees, is_editing, "student", :state_committees, :string) %>
	<%= edit_collection_end(is_editing) %>
	<%= edit_collection(is_editing) %>
	<%= govt_post_row("Local Posts:", @student.government_posts, is_editing, "student", 'Local', @local_posts) %>
	<%= student_row("Benevolent and Charitable Organizations:", @student.benevolent_and_charitable_organizations, is_editing, "student", :benevolent_and_charitable_organizations, :string) %>
	<%= edit_collection_end(is_editing) %>
<% end %>
</div>
<% if !is_editing %>
<hr class="clear_left" />
<% end %>
<% end %>
</div>
<% if user_signed_in? && !is_editing %>
<div class="edit_button">
	<%= create_button("Edit", edit_student_path(@student) + "?section=4", 'edit_btn') %>
</div>
<% end %>
<div id="edit_section_4" class="<%= 'hidden' if @show_4 != true %>">
<% if user_signed_in? || @relatives.length > 0 %>
<div class="student_data_div">
	<div class="student_data_header">Immediate Family <%= link_to "(Why only immediate family?)", { :controller => 'students', :action => 'why' } %></div>
<% if is_editing || @relatives.length > 0 %>
	<%= edit_collection(is_editing) %>
	<%= relative_rows(@relatives, is_editing) %>
	<%= edit_collection_end(is_editing) %>
<% end %>
</div>
<% if !is_editing %>
<hr class="clear_left" />
<% end %>
<% end %>
</div>
<% if user_signed_in? && !is_editing %>
<div class="edit_button">
	<%= create_button("Edit", edit_student_path(@student) + "?section=5", 'edit_btn') %>
</div>
<% end %>
<div id="edit_section_5" class="<%= 'hidden' if @show_5 != true %>">
<div class="student_data_div">
<% if user_signed_in? || @materials.length > 0 || @student.offsite_materials.length > 0 %>
	<div class="student_data_header">Related Objects and Documents</div>
<% end %>
<% if is_editing || @materials.length > 0 %>
	<div class="student_data_header_sub">In the Ledger:</div>
	<%= edit_collection(is_editing) %>
	<%= object_rows(@materials, is_editing) %>
	<%= edit_collection_end(is_editing) %>
<% end %>
<% if is_editing || @student.offsite_materials.length > 0 %>
	<div class="student_data_header_sub">Other:</div>
	<%= edit_collection(is_editing) %>
	<%= offsite_materials_row(@student, is_editing) %>
	<%= edit_collection_end(is_editing) %>
<% end %>
	<%= edit_collection(is_editing) %>
	<% citation = @student.citation_of_attendance
	citation = "[We are currently working to update and confirm citations of attendance.]" if (citation == nil || citation.length == 0) && (@student.years_attended_lls.length > 0 || @student.years_attended_lfa.length > 0)
	%>
	<% if !is_editing && citation && citation.length > 0 %>
	<span class="tooltip"><%= image_tag("help_thumb.sm.gif", { :alt => "help" }) %><span class="citation_help_tooltip">
		The Citation of Attendance provides primary source documentation of the student’s attendance at the Litchfield Female Academy and/or the Litchfield Law School.  If a citation is absent, the student is thought to have attended but currently lacks primary source confirmation. <br /><br />
		Records for the schools were sporadic, especially in the formative years of both institutions.  If instructors kept comprehensive records for the Litchfield Female Academy or the Litchfield Law School, they do not survive.  Researchers and staff have identified students through letters, diaries, family histories and genealogies, and town histories as well as catalogues of students printed in various years.   Art and needlework have provided further identification of Female Academy Students, and Litchfield County Bar records document a number of Law School students. The history of both schools and the identification of the students who attended them owe credit to the early 20th century research and documentation efforts of Emily Noyes Vanderpoel and Samuel Fisher, and the late 20th century research and documentation efforts of Lynne Templeton Brickley and the Litchfield Historical Society staff.
	</span></span>
	<% end %>
	<%= student_row("CITATION OF ATTENDANCE:", citation, is_editing, "student", :citation_of_attendance, :string) %>
	<%= student_row("Secondary Sources:", @student.secondary_sources, is_editing, "student", :secondary_sources, :string) %>
	<%= edit_collection_end(is_editing) %>
</div>
</div>
<% if !is_editing %>
<hr class="clear_both" />
<% end %>

app/views/students/edit.html.erb
<%= form_for(@student) do |f| %>
<%= render :partial => 'form', :locals => { :is_editing => true } %>
  <div class="actions">
<%= create_submit_button("save", 'save_btn') %>
<%= create_button("cancel", { :controller => 'students', :action => :show, :id => @student.id }, 'cancel_btn') %>
<!-- <%= f.submit %><%= link_to 'Cancel', @student %> -->
  </div>
<% end %>

app/views/students/index.html.erb
<div class="title">QUERY</div>
<%= form_tag({ :controller => 'students', :action => 'index' }, :method => "get") do %>
<%= text_field_tag(:qq, @query_string, :class => 'results_search') %>
<input id="search_btn" type="submit" value="" />
<% end %>

<% if @suggestions %>
<div class="suggestions">Did you mean: <span><%= link_to(@suggestions, :controller => 'students', :action => 'index', :q => @suggestions) %></span></div>
<% end %>
<% if @error_msg %>
<div class="search_error">Error: <span><%= @error_msg %></span></div>
<% end %>
<h2 class="page_subheader">Search Results (Total Found: <%= number_with_delimiter(@total_hits) %>)</h2>
<input type="checkbox" id="show_only_students" <%= "checked=checked" if session[:search_only_students] == 'true' %>>Show only students at LFA or LLS</input>
<%= render :partial => '/common/pagination', :locals => { :curr_page => @curr_page, :total_pages => @total_pages, :url => { :controller => 'students', :action => 'index', :qq => @query_string } } %>
<table class="results">
  <tr>
    <th>Name</th>
	  <th>Category</th>
    <th>Attended</th>
    <th>Attendance Dates</th>
    <th>Profession(s)</th>
    <th>Born</th>
    <th>Died</th>
<!--    <th></th>
    <th></th>-->
  </tr>

<% @students.each do |student| %>
  <tr>
<% if student.kind_of?(Student) %>
    <td><%= link_to student.name, student %></td>
	<td><%= student.school && student.school.length > 0 ? "Student" : "Non-student" %></td>
    <td><%= student.school %></td>
    <td><%= student.years_attended %></td>
    <td><%= list_professions(student.professions) %></td>
    <td><%= VagueDate.factory(student.born).get_year() if student.born && student.born.length > 0 %></td>
    <td><%= VagueDate.factory(student.died).get_year() if student.died && student.died.length > 0 %></td>
<!--    <td><%= link_to 'Edit', edit_student_path(student) %></td>
    <td><%= link_to 'Destroy', student, :confirm => 'Are you sure?', :method => :delete %></td>-->
  </tr>
<% else %>
  <tr>
    <td><%= link_to student.name, student %></td>
	<td>Object</td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
<!--    <td><%= link_to 'Edit', edit_student_path(student) %></td>
    <td><%= link_to 'Destroy', student, :confirm => 'Are you sure?', :method => :delete %></td>-->
<% end %>
  </tr>
<% end %>
</table>
<%= render :partial => '/common/pagination', :locals => { :curr_page => @curr_page, :total_pages => @total_pages, :url => { :controller => 'students', :action => 'index', :qq => @query_string } } %>
<div class="clear_both"></div>
<hr />

app/views/students/new.html.erb
<%= form_for(@student) do |f| %>
<%= render :partial => 'form', :locals => { :is_editing => true } %>
  <div class="actions">
<%= create_submit_button("save", 'save_btn') %>
<%= create_button("cancel", { :controller => 'admin', :action => 'index' }, 'cancel_btn') %>
 <!--   < %= f.submit('') %><%= link_to 'Cancel', { :controller => 'admin', :action => 'index' } %> -->
  </div>
<% end %>

app/views/students/show.html.erb
<%= render :partial => 'form', :locals => { :is_editing => false } %>
<%= render :partial => '/common/contact_us' %>

app/views/students/why.html.erb
<h1 class="page_header">Why only immediate family?</h1>

<p class="explanatory_text">
In addition to the individual pages created for the students and instructors of the Litchfield Law School and Litchfield Female Academy, pages are also created for their parents
and for any siblings who attended the school. While some genealogical research has been done for many of the students, including a record for their ancestors or links to cousins, aunts, uncles, etc.
on the database would make it unwieldy and the job of collecting data impossible. If you are looking for genealogical information regarding a particular student, please contact the Historical Society.
Staff will be happy to share any other information collected about the students. Currently, parent pages contain very little data. As more information becomes available it will be added to their biographies.
Please contact us if you have more information about students or parents that you would like to share.
</p>