config/routes.rb
Litchfield::Application.routes.draw do
    devise_for :users do
      get "/sign_in" => "devise/sessions#new"
      get "/sign_out" => "devise/sessions#destroy"
    end
    match 'sign_up' => 'admin#new_user'
    match '/create_user', :to => 'admin#create_user', :via => :post
    match 'edit_user' => 'admin#edit_user'
    match '/update_user', :to => 'admin#update_user', :via => :post
    match '/destroy_user', :to => 'admin#destroy_user', :via => :post
  
    match '/admin', :to => 'admin#index'
  
    get 'contact_us' => 'home#contact_us'
    post 'home/mail' => 'home#mail'
  
    match 'admin/validate_date' => 'admin#validate_date'
  
    match 'search/advanced' => 'search#advanced'
    match 'search/autocomplete' => 'search#autocomplete'
    match 'browse' => 'browse#index'
    match 'search' => 'search#index'
    match 'search/help' => 'search#help'
    match 'about' => 'search#about'
    match 'studies' => 'studies#index'
    match 'studies/history' => 'studies#history'
    match 'studies/history_school' => 'studies#history_school'
    match 'studies/history_lfa' => 'studies#history_lfa'
    match 'studies/lls_bibliography' => 'studies#lls_bibliography'
    match 'studies/lfa_bibliography' => 'studies#lfa_bibliography'
    match 'admin' => 'admin#index'
    match 'students/why' => 'students#why'
    match 'students/limit' => 'students#limit'
    match 'admin/new_row' => 'admin#new_row'
  
    match 'test_exception_notifier' => 'application#test_exception_notifier'
  
    match 'students/export_data' => 'students#export_data'
    match 'materials/export_data' => 'materials#export_data'
    match 'admin/account_maintenance' => 'admin#account_maintenance'
    post 'materials/add_transcription/:id' => 'materials#add_transcription'
    post 'materials/add_image/:id' => 'materials#add_image'
    post 'materials/remove_transcription/:id' => 'materials#remove_transcription'
    post 'materials/remove_image/:id' => 'materials#remove_image'
  
    resources :admin
  
    resources :materials
  
    resources :students
  
    root :to => "home#index"
  
  
  
  
  
  
  
  
  
  
  
end
  

app/views/admin/_column.html.erb
<%#
# ------------------------------------------------------------------------
#     Copyright 2010 Litchfield Historical Society
# ----------------------------------------------------------------------------
%>
<%# column: params: string header_img, string button_img, string new_path, string obj_controller, ActiveRecord array revised %>
<style type="text/css">
	.admin_column h2.<%= obj_controller %> { background:url(images/<%= header_img %>) top left no-repeat; }
	.admin_column_button.<%= obj_controller %> { background:url(images/<%= button_img %>) top left no-repeat; }
</style>

<div class="admin_column">
	<h2 class="<%= obj_controller %>"></h2>
	<div class="admin_column_top">
	<%= link_to "", new_path, { :class => "admin_column_button #{obj_controller}" } %>
	</div>
	<div class="admin_revised">
		<h3>Recently Revised ...</h3>
<% if revised && revised.length %>
		<ul class="revised">
<% for rec in revised %>
			<li><%= sday_format(rec.updated_at) %> <%= link_to rec.name, { :controller => obj_controller, :action => 'show', :id => rec.id } %></li>
<% end %>
		</ul>
<% else %>
		(No revised items)
<% end %>
		<br /><br />
		<div><%= link_to "Export Data", :controller => obj_controller, :action => 'export_data' %></div>
	</div>
</div>

app/views/admin/_sign_in.html.erb
<%#
# ------------------------------------------------------------------------
#     Copyright 2010 Litchfield Historical Society
# ----------------------------------------------------------------------------
%>
<%# sign_in: no params %>
<div class="sign_in">
	<div class="sign_in_logo"><%= image_tag('sign_in_logo.png') %></div>
 To enter the administration section, please <%= link_to "sign in", sign_in_path %>
</div>

app/views/admin/account_maintenance.html.erb
<h1 class="page_header">Ledger Account Maintenance</h1>

<table class="results">
  <tr>
    <th>Email</th>
    <th>Permissions</th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.email %></td>
    <td><%= user.permissions %></td>
    <td><%= link_to 'Edit', { :controller => 'admin', :action => 'edit_user', :id => user.id } %></td>
	<td><%= link_to 'Delete', "/destroy_user?id=#{user.id}", { :class => 'fxn_confirm', 'data-confirm' => "Are you sure you want to delete the user #{user.email}?", 'data-method' => 'post' } %>
<%#= link_to 'Delete', user_registration_path, :confirm => 'Are you sure?', :method => :delete %>
	</td>
  </tr>
<% end %>
</table>
<%= link_to "Add User", sign_up_path %>
<div class="clear_both"></div>

app/views/admin/edit_user.html.erb
<div class="devise_outer">
<h2>Edit <%= @resource_name.to_s.humanize %> <%= @user.email %></h2>

<%= form_for(@resource, :as => @resource_name, :url => { :controller => 'admin', :action => 'update_user' }) do |f| %>
<input type="hidden" name="id" value="<%= @user.id %>" />
  <%#= devise_error_messages! %>

  <p><%= f.label :permissions %><br />
  <%= f.select :permissions, [ 'Administrator', 'Full', 'Maintenance' ], { :selected => @user.permissions } %></p>
  <div>Administrator: can create users and manage accounts</div>
  <div>Full: can delete records</div>
  <div>Maintenance: can and and edit records</div>

  <p><%= f.submit "Update" %></p>
<% end %>

<%= link_to "Back", :back %>
</div>

app/views/admin/index.html.erb
<% if admin_signed_in? %>
	<div class="admin_users"><%= link_to("Account Maintenance", { :controller => 'admin', :action => 'account_maintenance' }) %></div>
<% end %>
<h1 class="page_header">Ledger Administration Home</h1>
<% if user_signed_in? %>
	<hr />
	<%= form_tag({ :controller => 'students', :action => 'index' }, :method => "get") do %>
		<div class="admin_search"><input id="search_btn" type="submit" value="" /></div>
		<div class="advanced_search_label">Search:<br /><div class="subtle">(Will search all fields)</div></div>
		<div class="advanced_search_input">
	<%= text_field_tag(:q, nil, {:class => 'admin_search_input'}) %>
		</div>
	<% end %>
	<div class="clear_left"></div>
	<hr />

	<%= render :partial => 'column', :locals => { :header_img => "admin_header_people.gif", :button_img => 'admin_button_people.jpg', :new_path => new_student_path, :obj_controller => 'students', :revised => @revised_people } %>
	<%= render :partial => 'column', :locals => { :header_img => "admin_header_object.gif", :button_img => 'admin_button_object.jpg', :new_path => new_material_path, :obj_controller => 'materials', :revised => @revised_objects } %>
<% elsif User.all.count == 0 %>
	There have been no users created. To begin administering this site, create a master user: <%= link_to "sign up", sign_up_path %>
<% else  %>
	<%= render :partial => 'sign_in' %>
<% end %>

app/views/admin/new_user.html.erb
<div class="devise_outer">
<h2>Create user</h2>

<%= form_for(@resource, :as => @resource_name, :url => { :controller => 'admin', :action => 'create_user' }) do |f| %>
  <%#= devise_error_messages! %>

  <p><%= f.label :email %><br />
  <%= f.text_field :email %></p>

  <p><%= f.label :password %><br />
  <%= f.password_field :password %></p>

  <p><%= f.label :password_confirmation %><br />
  <%= f.password_field :password_confirmation %></p>

  <p><%= f.label :permissions %><br />
  <%= f.select :permissions, [ 'Administrator', 'Full', 'Maintenance' ] %></p>
  <div>Administrator: can create users and manage accounts</div>
  <div>Full: can delete records</div>
  <div>Maintenance: can and and edit records</div>
  <p><%= f.submit "Create" %></p>
<% end %>

<%#= render :partial => "devise/shared/links" %>
</div>