config/routes.rb
Litchfield::Application.routes.draw do
    devise_for :users do
      get "/sign_in" => "devise/sessions#new"
      get "/sign_out" => "devise/sessions#destroy"
    end
    match 'sign_up' => 'admin#new_user'
    match '/create_user', :to => 'admin#create_user', :via => :post
    match 'edit_user' => 'admin#edit_user'
    match '/update_user', :to => 'admin#update_user', :via => :post
    match '/destroy_user', :to => 'admin#destroy_user', :via => :post
  
    match '/admin', :to => 'admin#index'
  
    get 'contact_us' => 'home#contact_us'
    post 'home/mail' => 'home#mail'
  
    match 'admin/validate_date' => 'admin#validate_date'
  
    match 'search/advanced' => 'search#advanced'
    match 'search/autocomplete' => 'search#autocomplete'
    match 'browse' => 'browse#index'
    match 'search' => 'search#index'
    match 'search/help' => 'search#help'
    match 'about' => 'search#about'
    match 'studies' => 'studies#index'
    match 'studies/history' => 'studies#history'
    match 'studies/history_school' => 'studies#history_school'
    match 'studies/history_lfa' => 'studies#history_lfa'
    match 'studies/lls_bibliography' => 'studies#lls_bibliography'
    match 'studies/lfa_bibliography' => 'studies#lfa_bibliography'
    match 'admin' => 'admin#index'
    match 'students/why' => 'students#why'
    match 'students/limit' => 'students#limit'
    match 'admin/new_row' => 'admin#new_row'
  
    match 'test_exception_notifier' => 'application#test_exception_notifier'
  
    match 'students/export_data' => 'students#export_data'
    match 'materials/export_data' => 'materials#export_data'
    match 'admin/account_maintenance' => 'admin#account_maintenance'
    post 'materials/add_transcription/:id' => 'materials#add_transcription'
    post 'materials/add_image/:id' => 'materials#add_image'
    post 'materials/remove_transcription/:id' => 'materials#remove_transcription'
    post 'materials/remove_image/:id' => 'materials#remove_image'
  
    resources :admin
  
    resources :materials
  
    resources :students
  
    root :to => "home#index"
  
  
  
  
  
  
  
  
  
  
  
end
  

app/models/material.rb
class Material < ActiveRecord::Base
	has_many :material_images
	has_many :images, :through => :material_images
	has_many :material_transcriptions
	has_many :transcriptions, :through => :material_transcriptions
	has_many :student_materials
	has_many :students, :through => :student_materials
	has_many :material_categories
	has_many :categories, :through => :material_categories

	validates :name, :presence => true
	validate :legal_number?
	validate :legal_date?
	validate :legal_viewing_aid?

	def legal_number?
		if object_id.blank? && accession_num.blank?
			errors.add(:id, "You must specify either an Object Id or an Accession Number")
		end
	end

	def legal_viewing_aid?
		errors.add(:viewing_aid, "Online viewing aid field must be a url starting with http://") if url && url.length > 0 && url.index('http://') != 0
	end

	def legal_date?
		if material_date && material_date.length > 0
			d = VagueDate.factory(material_date)
			errors.add(:date, d) if d.kind_of?(String)
		end
	end

#	include Paperclip
#	path = "/transcriptions/:id/:basename.:extension"
#	has_attached_file :transcription,
#		:url  => path,
#		:path => ":rails_root/public/#{path}"
#	validates_attachment_content_type(:transcription, { :content_type => ['application/pdf'] })

	def to_solr()
		categories = []
		self.categories.each { |rec|
			categories.push(rec.title)
		}

		solr = { :id => self.id,
			:doc_type => 'material',
			:name => self.name,
			:ac_name => self.name,
			:object_id => self.object_id,
			:accession_num => self.accession_num,
			:category => categories,
			:author => self.author,
			:material_date => VagueDate.year(self.material_date),
			:collection => self.collection,
			:held_at => self.held_at,
			:medium => self.medium,
			:size => self.size,
			:description => self.description
		}
		return solr
	end

	def generate_unique_name()
		others = Material.find_all_by_original_name(self.original_name)
		if others.length == 0 || (others.length == 1 && others[0].id == self.id)
			self.name = self.original_name
			return false
		end

		# use either object_id or accession_num, plus material_date if it exists
		append = ''
#		if self.accession_num && self.accession_num.length > 0
#			append = self.accession_num
#		elsif self.object_id && self.object_id.length > 0
#			append = self.object_id
#		end
		if self.material_date && self.material_date.length > 0
			append += "- #{self.material_date}"
		elsif self.author && self.author.length > 0
			append += "by #{self.author}"
		end

		self.name = "#{self.original_name} #{append}"

		# now be sure that it is unique
		matches = Material.find_all_by_name(self.name)
		index = 2
		ideal_unique_name = self.name
		while matches.length > 1 || (matches.length == 1 && matches[0].id != self.id)
			self.name = "#{ideal_unique_name} ##{index}"
			index += 1
			matches = Material.find_all_by_name(self.name)
		end
		return true
	end

	def fill_record()
	end

	def self.convert_solr_response(doc)
		if doc['doc_type'] == 'material'
			arr = doc['id'].split('_')
			if arr.length == 2 && arr[0] == 'material'
				rec = Material.find_by_id(arr[1])
				if rec != nil
					rec.fill_record()
					return rec
				else
					puts "Solr returned a material record that is not in the database: #{doc['name']}"
				end
			else
				puts "Solr returned a record of type #{arr[0]} when expecting a material: #{doc['name']}"
			end
		else
			puts "Solr returned a record of type #{doc['doc_type']} when expecting a material: #{doc['name']}"
		end
		return nil
	end
	
	def self.create_query_string(params)
		arr = []
		arr.push("doc_type:material")
		if params[:q] && params[:q].length > 0
			a = params[:q].split(' ')
			arr.push(a.join(' AND '))
		end
		if params[:repository] && params[:repository].length > 0
			arr.push( "held_at:#{params[:repository]}")
		end
		if params[:category] && params[:category].length > 0
			arr.push( "category:#{params[:category]}")
		end
		str = Student.assemble_date_query_string(params, 'material_date', :date_type, :date_first, :date_second)
		arr.push(str) if str
		return arr.join(' AND ')
	end

#	def self.validate_all(fields)
#		errors = []
#		errors.push("Name must not be blank") if fields['name'] == nil || fields['name'].length == 0
#		if fields['material_date'] && fields['material_date'].length > 0
#			d = VagueDate.factory(fields[:material_date])
#			errors.push("Date: #{d}") if d.kind_of?(String)
#		end
#		errors.push("Online viewing aid field must be a url starting with http://") if fields['url'] && fields['url'].length > 0 && fields['url'].index('http://') != 0
#		# todo: transcription and images is a file object
#		return errors
#	end

	def remove_references()
		# This removes all the other entries in other tables for this material
		recs = MaterialImage.find_all_by_material_id(self.id)
		recs.each { |rec|
			other = Image.find(rec.image_id)
			other.destroy
			rec.destroy()
		}
		recs = MaterialTranscription.find_all_by_material_id(self.id)
		recs.each { |rec|
			other = Transcription.find(rec.transcription_id)
			other.destroy
			rec.destroy()
		}
		StudentMaterial.remove_material(self.id)

		MaterialCategory.remove_material(self.id)
	end
end

app/controllers/materials_controller.rb
class MaterialsController < ApplicationController
	before_filter :authenticate_user!, :only => [:new, :edit, :create, :update, :destroy, :export_data]

	def format_for_export(str)
		return '' if str == nil
		str = str.gsub('"', "'")
		if str.index(',')
			str = "\"#{str}\""
		end
		return str
	end

	def export_data
		materials = Material.all
		out_file = File.new("#{Rails.root}/public/materials.csv", 'w')
		out_file.puts "id,name,unique_name,object_id,accession_num,url,author,date,collection,held_at,associated_place,medium,size,description,private_notes,categories,images,associated_objects,transcriptions,students"
		materials.each {|material|
			row = "#{material.id},#{format_for_export(material.original_name)},#{format_for_export(material.name) if material.original_name != material.name},#{format_for_export(material.object_id)},#{format_for_export(material.accession_num)},#{format_for_export(material.url)},#{format_for_export(material.author)},"
			row += "#{format_for_export(material.material_date)},#{format_for_export(material.collection)},#{format_for_export(material.held_at)},#{format_for_export(material.associated_place)},#{format_for_export(material.medium)},#{format_for_export(material.size)},"
			row += "#{format_for_export(material.description)},#{format_for_export(material.private_notes)},"
			coll = []
			material.categories.each { |category|
				coll.push(category.title)
			}
			row += "#{format_for_export(coll.join(';'))},"
			coll = []
			material.images.each { |image|
				coll.push("#{image.photo_file_name} - #{image.transcription}")
			}
			row += "#{format_for_export(coll.join(';'))},"
			coll = []
			mats = MaterialMaterial.find_all_by_material1_id(material.id)
			mats.each { |mat|
				coll.push("#{Material.find(mat.material2_id).name} - #{mat.description1}/#{mat.description2};")
			}
			mats = MaterialMaterial.find_all_by_material2_id(material.id)
			mats.each { |mat|
				coll.push("#{Material.find(mat.material1_id).name} - #{mat.description1}/#{mat.description2};")
			}
			row += "#{format_for_export(coll.join(';'))},"
			coll = []
			material.transcriptions.each { |transcription|
				coll.push("#{transcription.title} - #{transcription.pdf_file_name}")
			}
			row += "#{format_for_export(coll.join(';'))},"
			coll = []
			material.students.each { |student|
				coll.push("#{student.name}")
			}
			row += "#{format_for_export(coll.join(';'))}"
			out_file.puts row.gsub("\n", ' ').gsub("\r", ' ')
		}
		out_file.close()
		redirect_to "/ledger/materials.csv"
	end

	# GET /materials
	# GET /materials.xml
	def index
		@page_title = 'Object List'
		@materials = Material.all

		respond_to do |format|
			format.html # index.html.erb
			format.xml  { render :xml => @materials }
		end
	end

	# GET /materials/1
	# GET /materials/1.xml
	def show
		if params[:iterate] == 'next'
			params[:id] = params[:id].to_i + 1
			if Material.find_by_id(params[:id]) == nil
				params[:id] = 1
			end
		end
		if params[:iterate] == 'prev'
			params[:id] = params[:id].to_i - 1
			if Material.find_by_id(params[:id]) == nil
				params[:id] = 1
			end
		end
		@page_title = 'Object'
		@material = Material.find(params[:id])
		find_students()
		find_materials()

		respond_to do |format|
			format.html # show.html.erb
			format.xml  { render :xml => @material }
		end
	end

	# GET /materials/new
	# GET /materials/new.xml
	def new
		@material = Material.new
		new_setup()

		respond_to do |format|
			format.html # new.html.erb
			format.xml  { render :xml => @material }
		end
	end

	def new_setup
		@page_title = 'New Object'
		@students = []
		@materials = []
		@categories = Category.all().sort { |a, b| a.title <=> b.title }
		@categories.collect! {|rec| [ rec.id, rec.title ] }
		@categories.unshift([-2, ''])
	end

	# GET /materials/1/edit
	def edit
		@material = Material.find(params[:id])
		edit_setup()
	end

	def edit_setup
		@page_title = 'Edit Object'
		find_students()
		find_materials()
		@categories = Category.all().sort { |a, b| a.title <=> b.title }
		@categories.collect! {|rec| [ rec.id, rec.title ] }
		@categories.unshift([-2, ''])
	end

	def add_image
		if params[:file]
			img = Image.new
			img.photo = params[:file]
			img.save
			MaterialImage.create({ :material_id => params[:id], :image_id => img.id })
		end

		redirect_to :back
	end

	def add_transcription
		if params[:file]
			img = Transcription.new
			img.pdf = params[:file]
			# TODO-PER: Hack in a title for now from the file name
			title = img.pdf_file_name
			img.title = title.gsub(".pdf", "").gsub(".PDF", "").gsub("_", " ")
			img.save
			MaterialTranscription.create({ :material_id => params[:id], :transcription_id => img.id })
		end

		redirect_to :back
	end

	def remove_transcription
		id = params[:id]
		rec = MaterialTranscription.find_by_transcription_id(id)
		rec.destroy() if rec != nil
		rec = Transcription.find_by_id(id)
		rec.destroy() if rec != nil
		redirect_to :back
	end

	def remove_image
		id = params[:id]
		rec = MaterialImage.find_by_image_id(id)
		rec.destroy() if rec != nil
		rec = Image.find_by_id(id)
		rec.destroy() if rec != nil
		redirect_to :back
	end

	# POST /materials
	# POST /materials.xml
	def create
		p = params[:material]
		hash = { :original_name => p['original_name'], :object_id => p['object_id'], :accession_num => p['accession_num'],
			:url => p['url'],  :author => p['author'], :material_date => VagueDate.factory(p['material_date']).to_s,
			:collection => p['collection'], :held_at => p['held_at'], :associated_place => p['associated_place'], :medium => p['medium'],
			:size => p['size'], :description => p['description'], :private_notes => p['private_notes']
		}
		@material = Material.new(hash)
		@material.generate_unique_name()

		respond_to do |format|
			if @material.save
				categories = parse_array(p['category'])
				categories.each {|category|
					if category['name'].to_i > 0
						MaterialCategory.add_connection(@material.id, category['name'].to_i)
					elsif !category['writein'].blank?
						MaterialCategory.add(@material.id, category['writein'])
					end
				}
				students = parse_array(p['assoc'])
				students.each {|student|
					rec = Student.get_or_create({ :name => student })
					if rec
						StudentMaterial.create({ :student_id => rec.id, :material_id => @material.id })
					end
				}

				Browse.material_changed(@material, nil)
				solr().add_object(@material.to_solr())
				format.html { redirect_to(@material, :notice => 'The object was successfully created.') }
			else
				format.html {
					new_setup()
					render :action => "new"
				}
			end
		end
	end

	# PUT /materials/1
	# PUT /materials/1.xml
	def update
		material_orig = Material.find(params[:id]).to_solr
#		@errors = Material.validate_all(params['material'])
		@material = Material.find(params[:id])
#		if @errors.length == 0
			analyze_update_params(params, 'material')	# TODO-PER: debugging code
#			redirect_to(@material, :notice => 'NOTICE: During initial testing, the modification of objects has been turned off.')
#			return
			p = params[:material]
			hash = { :original_name => p['original_name'], :object_id => p['object_id'], :accession_num => p['accession_num'],
				:url => p['url'],  :author => p['author'], :material_date => VagueDate.factory(p['material_date']).to_s,
				:collection => p['collection'], :held_at => p['held_at'], :associated_place => p['associated_place'], :medium => p['medium'],
				:size => p['size'], :description => p['description'], :private_notes => p['private_notes']
			}
			@material.original_name = p['original_name']
			@material.generate_unique_name()
			ok = @material.update_attributes(hash)
#		else
#			ok = false
#		end

		respond_to do |format|
			if ok
				format.html {
					MaterialCategory.remove_material(@material.id)
					categories = parse_array(p['category'])
					categories.each {|category|
						if category['name'].to_i > 0
							MaterialCategory.add_connection(@material.id, category['name'].to_i)
						else
							MaterialCategory.add(@material.id, category['writein'])
						end
					}
					StudentMaterial.remove_material(@material.id)
					students = parse_array(p['assoc'])
					relationships = parse_array(p['assoc_relationship'])
					material_comment = parse_array(p['assoc_material_comment'])
					students.each_with_index {|student, i|
						rec = Student.get_or_create({ :name => student })
						if rec
							StudentMaterial.create({ :student_id => rec.id, :material_id => @material.id, :relationship => relationships[i], :material_comment => material_comment[i] })
						end
					}
					MaterialMaterial.remove_material(@material.id)
					materials = parse_array(p['mat_assoc'])
					description1 = parse_array(p['mat_assoc_description1'])
					description2 = parse_array(p['mat_assoc_description2'])
					materials.each_with_index {|material, i|
						rec = Material.find_by_name(material)
						if rec
							MaterialMaterial.factory(@material.id, rec.id, description1[i], description2[i])
						end
					}
					if p['transcriptions']
						titles = parse_array(p['transcriptions']['title'])
						transcription_recs = MaterialTranscription.find_all_by_material_id(@material.id)
						transcription_recs.each_with_index { |rec, i|
							title = titles.length > i ? titles[i] : ''
							trans = Transcription.find(rec.transcription_id)
							trans.title = title
							trans.save()
						}
					end

					if p['images']
						images = parse_hash(p['images']['transcription'])
						image_recs = @material.images # MaterialImage.find_all_by_material_id(@material.id)
						@material.images.sort { |a,b| a.id <=> b.id }.each_with_index { |rec, i|
							#tran = images.length > i ? images[i] : ''
							#im = Image.find(rec.image_id)
							#im.transcription = tran
							#im.save()
							if images[rec.id.to_s] && rec.transcription != images[rec.id.to_s]
								rec.transcription = images[rec.id.to_s]
								rec.save
							end
						}
					end

					# Now that all the other data has been set, recreate the unique name

app/helpers/materials_helper.rb
module MaterialsHelper
#	def list_transcriptions(list)
#		return "" if list == nil || list.length == 0
#		lines = []
#		list.each_with_index {|rec, i|
#			lines.push(link_to(rec.title, rec.pdf.url))
#		}
#		return lines.join("<br />")
#	end
end

app/views/materials/_form.html.erb
<%#
# ------------------------------------------------------------------------
#     Copyright 2010 Litchfield Historical Society
# ----------------------------------------------------------------------------
# MATERIALS
%>
<%# form: params: bool is_editing %>
<% if params[:iterate] %>
<div style="position: absolute;top:220px;">
<%= link_to "Next", :controller => 'materials', :action => 'show', :id => @material.id, :iterate => 'next' %></div>
<% end %>
<% if user_signed_in? && !is_editing %>
<div class="edit_button">
	<%= create_button("Delete", { :controller => 'materials', :action => 'destroy', :id => @material.id }, 'delete_btn fxn_confirm', { 'data-confirm' => 'Are you sure you want to delete this object?', 'data-method' => 'delete' })  if full_signed_in? %>
	<%= create_button("Edit", edit_material_path(@material), 'edit_btn') %>
</div>
<% end %>
<div class="student_data_div">
	<p class="student_name"><%= name_row(@material.original_name, is_editing, "Object") %></p>
</div>
<%= custom_error_messages_helper(@material) %>
<% if !is_editing %>
<hr />
<% if user_signed_in? && !is_editing %>
<div>
	<%= create_button("Add Image", { :controller => 'materials', :action => 'add_image', :id => @material.id }, 'add_image_btn fxn_add_image')  if full_signed_in? %>
</div>
<% end %>
<%= images_rows(@material.images, is_editing, user_signed_in?) %>
<hr />
<% end %>
<div class="student_data_div">
	<%= edit_collection(is_editing) %>
	<%= name_row_edit(@material.original_name, is_editing, "material") %>
	<%= student_row("Object ID:", @material.object_id, is_editing, "material", :object_id, :input) %>
	<%= student_row("Accession #:", @material.accession_num, is_editing, "material", :accession_num, :input) %>
	<%= edit_collection_end(is_editing) %>
	<%= edit_collection(is_editing) %>
	<% cats = @material.name.blank? ? " " : list_professions(@material.categories) %>
	<%= student_row("Category:", cats, is_editing, "material", :category, :multiple_select, @categories) %>
	<%= edit_collection_end(is_editing) %>
	<%= edit_collection(is_editing) %>
	<%= student_row("Medium:", @material.medium, is_editing, "material", :medium, :input) %>
	<%= student_row("Creator:", @material.author, is_editing, "material", :author, :input) %>
	<%= student_row("Date:", @material.material_date, is_editing, "material", :material_date, :date) %>
	<%= student_row("Collection:", @material.collection, is_editing, "material", :collection, :input) %>
	<%= student_row("Held at:", @material.held_at, is_editing, "material", :held_at, :input) %>
	<%= student_row("Associated Place:", @material.associated_place, is_editing, "material", :associated_place, :input) %>
	<%= student_row("Size:", @material.size, is_editing, "material", :size, :input) %>
	<%= student_row("Description:", @material.description, is_editing, "material", :description, :string) %>
	<%= student_row("Private Notes:", @material.private_notes, is_editing, "material", :private_notes, :string) if user_signed_in? %>
	<%= student_row("", @material.url ? @material.url : "", is_editing, "material", :url, :url, 'View online finding aid') %>
	<%= edit_collection_end(is_editing) %>
<% if user_signed_in? && !is_editing %>
<div>
	<%= create_button("Add Transcription", { :controller => 'materials', :action => 'add_transcription', :id => @material.id }, 'add_transcription_btn fxn_add_transcription')  if full_signed_in? %>
</div>
<% end %>
	<%= edit_collection(is_editing) %>
	<%= transcriptions_rows(@material.transcriptions, is_editing, user_signed_in?) %>
	<%= edit_collection_end(is_editing) %>
</div>

<% if is_editing %>
<%= edit_collection(is_editing) %>
<%= images_rows(@material.images, is_editing, user_signed_in?) %>
<%= edit_collection_end(is_editing) %>
<% else %>
<hr class="clear_left" />
<% end %>
<% if is_editing || @students.length > 0 %>
<div class="student_data_div">
	<div class="student_data_header">Associated People</div>
	<%= edit_collection(is_editing) %>
	<%= people_rows(@students, is_editing) %>
	<%= edit_collection_end(is_editing) %>
</div>
<hr class="clear_left" />
<% end %>
<% if is_editing || @materials.length > 0 %>
<div class="student_data_div">
	<div class="student_data_header">Associated Objects</div>
	<%= edit_collection(is_editing) %>
	<%= assoc_objects_rows(@materials, is_editing) %>
	<%= edit_collection_end(is_editing) %>
</div>
<hr class="clear_left" />
<% end %>

app/views/materials/edit.html.erb
<%= raw(@errors.join("<br />")) if @errors && @errors.length > 0 %>
<%= form_for(@material, :html => {:multipart => true}) do |f| %>
<%= render :partial => 'form', :locals => { :is_editing => true } %>
  <div class="actions">
<%= create_submit_button("save", 'save_btn') %>
<%= create_button("cancel", { :controller => 'materials', :action => :show, :id => @material.id }, 'cancel_btn') %>
<!--    <%= f.submit("Update Object") %><%= link_to 'Cancel', @material %> -->
  </div>
<% end %>

app/views/materials/new.html.erb
<%= form_for(@material, :html => {:multipart => true}) do |f| %>
<%= render :partial => 'form', :locals => { :is_editing => true } %>
  <div class="actions">
<%= create_submit_button("save", 'save_btn') %>
<%= create_button("cancel", { :controller => 'admin', :action => 'index' }, 'cancel_btn') %>
<!--    <%= f.submit('Create Object') %><%= link_to 'Cancel', { :controller => 'admin', :action => 'index' } %> -->
  </div>
<% end %>

app/views/materials/show.html.erb
<%= render :partial => 'form', :locals => { :is_editing => false } %>
<%= render :partial => '/common/contact_us' %>