config/routes.rb
Litchfield::Application.routes.draw do
    devise_for :users do
      get "/sign_in" => "devise/sessions#new"
      get "/sign_out" => "devise/sessions#destroy"
    end
    match 'sign_up' => 'admin#new_user'
    match '/create_user', :to => 'admin#create_user', :via => :post
    match 'edit_user' => 'admin#edit_user'
    match '/update_user', :to => 'admin#update_user', :via => :post
    match '/destroy_user', :to => 'admin#destroy_user', :via => :post
  
    match '/admin', :to => 'admin#index'
  
    get 'contact_us' => 'home#contact_us'
    post 'home/mail' => 'home#mail'
  
    match 'admin/validate_date' => 'admin#validate_date'
  
    match 'search/advanced' => 'search#advanced'
    match 'search/autocomplete' => 'search#autocomplete'
    match 'browse' => 'browse#index'
    match 'search' => 'search#index'
    match 'search/help' => 'search#help'
    match 'about' => 'search#about'
    match 'studies' => 'studies#index'
    match 'studies/history' => 'studies#history'
    match 'studies/history_school' => 'studies#history_school'
    match 'studies/history_lfa' => 'studies#history_lfa'
    match 'studies/lls_bibliography' => 'studies#lls_bibliography'
    match 'studies/lfa_bibliography' => 'studies#lfa_bibliography'
    match 'admin' => 'admin#index'
    match 'students/why' => 'students#why'
    match 'students/limit' => 'students#limit'
    match 'admin/new_row' => 'admin#new_row'
  
    match 'test_exception_notifier' => 'application#test_exception_notifier'
  
    match 'students/export_data' => 'students#export_data'
    match 'materials/export_data' => 'materials#export_data'
    match 'admin/account_maintenance' => 'admin#account_maintenance'
    post 'materials/add_transcription/:id' => 'materials#add_transcription'
    post 'materials/add_image/:id' => 'materials#add_image'
    post 'materials/remove_transcription/:id' => 'materials#remove_transcription'
    post 'materials/remove_image/:id' => 'materials#remove_image'
  
    resources :admin
  
    resources :materials
  
    resources :students
  
    root :to => "home#index"
  
  
  
  
  
  
  
  
  
  
  
end
  

app/views/common/_admin_bar.html.erb
<%#
# ------------------------------------------------------------------------
#     Copyright 2010 Litchfield Historical Society
# ----------------------------------------------------------------------------
%>
<%# nav params: none %>
<% if user_signed_in? %>
		<div class="admin_banner">
			<div class="user_name"><%= current_user.email %> &bull; <%= link_to "Settings", edit_user_registration_path %> &bull; <%= link_to "Sign out", sign_out_path %></div>
			<%= link_to "Administration", { :controller => '/admin', :action => 'index' },{ :class => 'administration_title'} %>
		</div>
<% end %>

app/views/common/_contact_us.html.erb
<div class="student_data_header_sub">Contact Us</div>
<p>Do you have more information for the Ledger?</p>
<p>If you have family papers, objects, or any other details you would like to share, or if you would like to obtain a copy of an image for publication, please
contact us at <a href="mailto:curator@litchfieldhistoricalsociety.org">curator@litchfieldhistoricalsociety.org</a>.
<!--<%= link_to "contact us", {:controller => 'home', :action => 'contact_us' }, { :class => 'contact_us_link' } %>.-->
</p>

app/views/common/_nav.html.erb
<%#
# ------------------------------------------------------------------------
#     Copyright 2010 Litchfield Historical Society
# ----------------------------------------------------------------------------
%>
<%# nav params: bool show_home, string curr_tab, string id_suffix %>
<% curr_tab ||= '' %>
<div id="nav_container_<%= id_suffix %>">
	<%= create_tab_item(".", { :controller => '/search', :action => 'index' }, "ledger_search", curr_tab == 'search', 'Use keywords to locate individuals or objects.') %>
	<%= create_tab_item(".", { :controller => '/browse', :action => 'index' }, "ledger_browse", curr_tab == 'browse', 'View listings of students or objects by name, date, or place.') %>
	<%= create_tab_item(".", { :controller => '/studies', :action => 'index' }, "ledger_studies", curr_tab == 'studies', 'Read introductory essays, find bibliographies of secondary sources, or get ideas for research topics.') %>
	<%= create_tab_item(".", { :controller => '/search', :action => 'about' }, "ledger_about", curr_tab == 'about', 'Read about the funders and project team.') %>
<% if show_home %>
	<%= create_tab_item(".", { :controller => '/home', :action => 'index' }, "ledger_home", curr_tab == 'home') %>
<% end %>
</div>
<div class="clear_both"></div>

app/views/common/_pagination.html.erb
<%#
# ------------------------------------------------------------------------
#     Copyright 2010 Litchfield Historical Society
# ----------------------------------------------------------------------------
%>
<%# pagination: int curr_page, int total_pages, hash url %>
<% if total_pages > 1 %>
<% max_shown = 15 %>
<div class="pagination">
	<%= if curr_page > 0 && total_pages > max_shown
		my_link_to('First', url.merge({:page => 0}) )
	end %>
	<%= if curr_page > 0
		my_link_to('Previous', url.merge({:page => curr_page-1}) )
	end %>
	<% if total_pages > max_shown %>
		<% start = curr_page < max_shown ? 0 : curr_page - max_shown / 2
			last = start + max_shown
			if last > total_pages
				bump = last - total_pages + 1
				last -= bump
				start -= bump
			end
		%>
		<%= pagination_links(start, last, url, curr_page) %>
	<% else %>
		<%= pagination_links(0, total_pages-1, url, curr_page) %>
	<% end %>
	<%= if curr_page < total_pages-1
		my_link_to('Next', url.merge({:page => curr_page+1}))
	end %>
	<%= if curr_page < total_pages-1 && total_pages > max_shown
		my_link_to('Last', url.merge({:page => total_pages-1}))
	end %>
</div>
<% end %>